### ISSUE TITLE
CORS option

### ISSUE THREAD

**Issue by Jacq** [daq-tools/wireviz-web#7]
Hi, thanks for this wireviz web service interface.
Can you activate by default, or add a --cors flag to the cli, so Flask-CORS can be enabled for all routes? at: https://github.com/daq-tools/wireviz-web/blob/b109919cb691012b5704d6ca2057b9220a65d549/wireviz_web/__init__.py#L37

Thanks!
Jacq

**Comment by amotl** [comment]
Dear @Jacq,

thank you for writing in. Your proposal is a very good suggestion. Would you be friends enough with Python to be able to submit a corresponding patch?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Resolved with #9 and #10. Thank you, Jacq!

**Comment by amotl** [comment]
wireviz-web (0.4.0) has been published to PyPI, including your improvements.
